# Generated by Django 4.0.2 on 2022-02-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_application_name_alter_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.application'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.language'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='package',
            field=models.ManyToManyField(null=True, related_name='snippets', to='snippets.Package'),
        ),
    ]
