# Generated by Django 4.0.2 on 2022-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_codesnippet_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='packages',
            field=models.ManyToManyField(null=True, related_name='language', to='snippets.Package'),
        ),
    ]
