# Generated by Django 4.0.2 on 2022-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_language_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='package',
            field=models.ManyToManyField(related_name='snippets', to='snippets.Package'),
        ),
        migrations.AlterField(
            model_name='language',
            name='packages',
            field=models.ManyToManyField(related_name='language', to='snippets.Package'),
        ),
    ]
